import { initGraphQLTada } from "gql.tada";
import type { introspection } from "../../graphql-env.d.ts";

// Custom scalars emitted by HotChocolate in the Alberto Orders API.
// Update once schema.graphql is generated by the concurrent BFF agent.
export const graphql = initGraphQLTada<{
  introspection: introspection;
  scalars: {
    DateTime: string;
    Long: number;
    UUID: string;
  };
}>();

export type { FragmentOf, ResultOf, VariablesOf } from "gql.tada";
