<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <!--Azure.Identity vulnerabilities not fixed yet-->
    <NoWarn>NU1903;NU1904;NU1905</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet"/>
    <PackageReference Include="NBomber"/>
    <PackageReference Include="Respawn"/>
    <PackageReference Include="Testcontainers.PostgreSql"/>
    <PackageReference Include="Microsoft.Extensions.Logging.Console"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alberto.EventStore\Alberto.EventStore.csproj"/>
    <ProjectReference Include="..\Alberto.EventStore.InMemory\Alberto.EventStore.InMemory.csproj"/>
    <ProjectReference Include="..\Alberto.EventStore.Postgres\Alberto.EventStore.Postgres.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="BenchmarkDotNet.Artifacts\"/>
    <Folder Include="BenchmarkDotNet.Artifacts\results\"/>
  </ItemGroup>

</Project>
