using System.Text.Json;
using Alberto.SourceGeneration;
using Alberto.Tests.SampleEvents;
using FluentAssertions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace Alberto.Tests.SourceGeneration;

/// <summary>
/// Runs <see cref="EventRegistryGenerator"/> over real compilations that reference the real
/// <c>Alberto</c>. The JSON generator does not run inside the driver, so these assert on the
/// generated text and the generator's own diagnostics, not on the output compiling;
/// <c>Alberto.Tests.SampleEvents</c> and the AOT smoke app are where the output is compiled for real.
/// </summary>
public class EventRegistryGeneratorTests
{
    private const string Context = """
        [System.Text.Json.Serialization.JsonSerializable(typeof(Opened))]
        [System.Text.Json.Serialization.JsonSerializable(typeof(Noted))]
        internal partial class Ctx : System.Text.Json.Serialization.JsonSerializerContext;
        """;

    [Fact]
    public void Emits_a_descriptor_per_event_with_its_id_version_contract_and_tags()
    {
        var (sources, diagnostics) = Run($$"""
            namespace App;

            [EventType("opened", Version = 3, UpcastingNotRequired = true)]
            public sealed record Opened([property: Tag("account")] string AccountId, [property: Tag("owner")] System.Guid Owner, int Amount) : IEvent;

            [EventType("noted")]
            public sealed record Noted(string Text) : IEvent;

            {{Context}}

            [AlbertoEventRegistry(typeof(Ctx))]
            public static partial class Events;
            """);

        diagnostics.Should().BeEmpty();
        sources.Should().ContainSingle().Which.Should().Be("""
            // <auto-generated/>
            #nullable enable

            namespace App;

            partial class Events
            {
                /// <summary>Every [EventType] in this assembly, generated by Alberto from [AlbertoEventRegistry].</summary>
                public static global::Alberto.IEventTypeRegistry Registry { get; } = global::Alberto.EventTypeRegistry.CreateBuilder()
                    .Add(new global::Alberto.EventTypeDescriptor(
                        "noted", 1, false,
                        global::App.Ctx.Default.GetTypeInfo(typeof(global::App.Noted))!,
                        static _ => global::System.Array.Empty<global::System.Collections.Generic.KeyValuePair<string, object?>>()))
                    .Add(new global::Alberto.EventTypeDescriptor(
                        "opened", 3, true,
                        global::App.Ctx.Default.GetTypeInfo(typeof(global::App.Opened))!,
                        static e =>
                        {
                            var @event = (global::App.Opened)e;
                            return new global::System.Collections.Generic.KeyValuePair<string, object?>[]
                            {
                                new("account", @event.AccountId),
                                new("owner", @event.Owner),
                            };
                        }))
                    .Build();
            }

            """.ReplaceLineEndings());
    }

    [Fact]
    public void Emits_nothing_and_reports_nothing_without_the_attribute()
    {
        // Duplicate ids and a missing context would all be reported if the generator were
        // running; a consumer on the reflection path must see none of it.
        var (sources, diagnostics) = Run("""
            [EventType("same")] public sealed record A(object Tagless) : IEvent;
            [EventType("same")] public sealed record B([property: Tag("b")] object Value) : IEvent;
            """);

        sources.Should().BeEmpty();
        diagnostics.Should().BeEmpty();
    }

    [Fact]
    public void Registers_what_FromAssemblies_registers_and_nothing_else()
    {
        var (sources, _) = Run($$"""
            namespace App;

            [EventType("opened")] public record Opened([property: Tag("account")] string AccountId) : IEvent;
            [EventType("noted")] public sealed class Noted : IEvent { }
            [EventType("abstract")] public abstract record Abstract : IEvent;
            [EventType("not-an-event")] public sealed record NotAnEvent;
            public sealed record Derived(string AccountId) : Opened(AccountId);

            {{Context}}

            [AlbertoEventRegistry(typeof(Ctx))]
            public static partial class Events;
            """);

        var source = sources.Should().ContainSingle().Subject;
        source.Should().Contain("typeof(global::App.Opened)").And.Contain("typeof(global::App.Noted)");
        source.Should().NotContainAny("Abstract", "NotAnEvent", "Derived");
    }

    [Fact]
    public void Reads_tags_declared_on_a_base_type()
    {
        var (sources, _) = Run($$"""
            namespace App;

            public abstract record Base([property: Tag("account")] string AccountId) : IEvent;
            [EventType("opened")] public sealed record Opened(string AccountId, [property: Tag("owner")] string Owner) : Base(AccountId);
            [EventType("noted")] public sealed record Noted(string Text) : IEvent;

            {{Context}}

            [AlbertoEventRegistry(typeof(Ctx))]
            public static partial class Events;
            """);

        sources.Single().Should().Contain("""new("owner", @event.Owner),""")
            .And.Contain("""new("account", @event.AccountId),""");
    }

    [Fact]
    public void Nests_the_registry_inside_its_containing_types()
    {
        var (sources, _) = Run($$"""
            namespace App;

            [EventType("opened")] public sealed record Opened : IEvent;
            [EventType("noted")] public sealed record Noted : IEvent;

            {{Context}}

            public static partial class Outer
            {
                [AlbertoEventRegistry(typeof(Ctx))]
                public static partial class Events;
            }
            """);

        sources.Single().Should().Contain("partial class Outer\n{\npartial class Events\n{".ReplaceLineEndings());
    }

    [Fact]
    public void A_duplicate_id_is_ALB3001()
    {
        var (_, diagnostics) = Run($$"""
            namespace App;

            [EventType("same")] public sealed record Opened : IEvent;
            [EventType("same")] public sealed record Noted : IEvent;

            {{Context}}

            [AlbertoEventRegistry(typeof(Ctx))]
            public static partial class Events;
            """);

        diagnostics.Should().ContainSingle().Which.Id.Should().Be("ALB3001");
    }

    [Fact]
    public void An_event_missing_from_the_context_is_ALB3002_and_left_out()
    {
        var (sources, diagnostics) = Run($$"""
            namespace App;

            [EventType("opened")] public sealed record Opened : IEvent;
            [EventType("noted")] public sealed record Noted : IEvent;
            [EventType("forgotten")] public sealed record Forgotten : IEvent;

            {{Context}}

            [AlbertoEventRegistry(typeof(Ctx))]
            public static partial class Events;
            """);

        var diagnostic = diagnostics.Should().ContainSingle().Subject;
        diagnostic.Id.Should().Be("ALB3002");
        diagnostic.GetMessage().Should().Contain("global::App.Forgotten").And.Contain("global::App.Ctx");
        diagnostic.Location.Should().NotBe(Location.None);
        sources.Single().Should().NotContain("Forgotten");
    }

    [Theory]
    [InlineData("string")]
    [InlineData("System.Guid")]
    [InlineData("int")]
    [InlineData("long?")]
    [InlineData("System.DayOfWeek")]
    [InlineData("System.DateTimeOffset")]
    [InlineData("Id")]
    [InlineData("IdStruct")]
    [InlineData("System.IFormattable")]
    public void A_tag_type_with_its_own_ToString_is_accepted(string type)
    {
        TagDiagnostics(type).Should().BeEmpty();
    }

    [Theory]
    [InlineData("object")]
    [InlineData("Plain")]
    [InlineData("PlainStruct")]
    [InlineData("PlainStruct?")]
    [InlineData("int[]")]
    [InlineData("System.Collections.Generic.List<string>")]
    public void A_tag_type_without_its_own_ToString_is_ALB3003(string type)
    {
        TagDiagnostics(type).Should().ContainSingle().Which.Id.Should().Be("ALB3003");
    }

    private static IEnumerable<Diagnostic> TagDiagnostics(string type) => Run($$"""
        namespace App;

        public sealed record Id(System.Guid Value);
        public readonly record struct IdStruct(System.Guid Value);
        public sealed class Plain { }
        public struct PlainStruct { }

        [EventType("opened")] public sealed record Opened([property: Tag("t")] {{type}} Value) : IEvent;
        [EventType("noted")] public sealed record Noted : IEvent;

        {{Context}}

        [AlbertoEventRegistry(typeof(Ctx))]
        public static partial class Events;
        """).Diagnostics;

    [Fact]
    public void The_generated_registry_matches_the_reflection_registry()
    {
        var generated = SampleEventsRegistry.Registry;
#pragma warning disable IL2026, IL3050 // the reflection path is the reference being compared against
        var reflected = EventTypeRegistry.FromAssembly(typeof(SampleEventsRegistry).Assembly);
#pragma warning restore IL2026, IL3050

        generated.Descriptors.Select(d => d.Id).Should().BeEquivalentTo(reflected.Descriptors.Select(d => d.Id));

        IEvent[] samples =
        [
            new VersionedOrder(Guid.NewGuid(), 12.5m, "BE"),
            new PlainNote(Guid.NewGuid(), "hello"),
        ];

        foreach (var sample in samples)
        {
            generated.TryGetByType(sample.GetType(), out var g).Should().BeTrue();
            reflected.TryGetByType(sample.GetType(), out var r).Should().BeTrue();

            g!.Id.Should().Be(r!.Id);
            g.Version.Should().Be(r.Version);
            g.UpcastingNotRequired.Should().Be(r.UpcastingNotRequired);
            g.ClrType.Should().Be(r.ClrType);
            g.TagExtractor(sample).Should().Equal(r.TagExtractor(sample));

            // The same bytes on the way out, and the same case-insensitive reading on the way in:
            // a drift between the context's options and the reflection path's would change what
            // is stored.
            var json = JsonSerializer.Serialize(sample, g.JsonTypeInfo);
            json.Should().Be(JsonSerializer.Serialize(sample, r.JsonTypeInfo));
            var lowered = json.ToLowerInvariant().Replace("\"be\"", "\"BE\"");
            JsonSerializer.Deserialize(lowered, g.JsonTypeInfo).Should()
                .Be(JsonSerializer.Deserialize(lowered, r.JsonTypeInfo));
        }
    }

    internal static (IReadOnlyList<string> Sources, IReadOnlyList<Diagnostic> Diagnostics) Run(
        string source, IIncrementalGenerator? generator = null)
    {
        var compilation = CSharpCompilation.Create(
            "GeneratorProbe",
            [CSharpSyntaxTree.ParseText("global using Alberto;\n" + source,
                new CSharpParseOptions(LanguageVersion.Latest), cancellationToken: TestContext.Current.CancellationToken)],
            ReferenceSet,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var result = CSharpGeneratorDriver.Create(generator ?? new EventRegistryGenerator())
            .RunGenerators(compilation, TestContext.Current.CancellationToken)
            .GetRunResult();

        return (result.GeneratedTrees.Select(t => t.GetText().ToString()).ToList(), result.Diagnostics);
    }

    private static readonly IReadOnlyList<MetadataReference> ReferenceSet = BuildReferenceSet();

    private static IReadOnlyList<MetadataReference> BuildReferenceSet()
    {
        // Loaded assemblies only, so touch the ones the probe names first.
        _ = typeof(IEvent).Assembly;
        _ = typeof(System.Text.Json.Serialization.JsonSerializerContext).Assembly;

        return AppDomain.CurrentDomain.GetAssemblies()
            .Where(a => !a.IsDynamic && !string.IsNullOrEmpty(a.Location))
            .Select(a => (MetadataReference)MetadataReference.CreateFromFile(a.Location))
            .ToList();
    }
}
