using Alberto.SourceGeneration;
using FluentAssertions;
using Microsoft.CodeAnalysis;
using Xunit;

namespace Alberto.Tests.SourceGeneration;

/// <summary>
/// Runs <see cref="EvolverTableGenerator"/> over real compilations. The output compiling and
/// dispatching is covered by <c>SampleEvolver</c> in <c>Alberto.Tests.SampleEvents</c> and by the
/// AOT smoke app.
/// </summary>
public class EvolverTableGeneratorTests
{
    private const string Events = """
        namespace App;

        [EventType("opened")] public sealed record Opened : IEvent;
        [EventType("noted")] public sealed record Noted : IEvent;
        [EventType("other")] public sealed record Other : IEvent;
        public sealed class State { }
        public sealed class OtherState { }
        """;

    private const string Registry = """
        [System.Text.Json.Serialization.JsonSerializable(typeof(Opened))]
        internal partial class Ctx : System.Text.Json.Serialization.JsonSerializerContext;

        [AlbertoEventRegistry(typeof(Ctx))]
        public static partial class Registry;
        """;

    [Fact]
    public void Emits_a_table_entry_per_IEvolve_of_the_evolvers_state()
    {
        var (sources, diagnostics) = Run($$"""
            {{Events}}

            public sealed partial class AccountEvolver : Evolver<State>, IEvolve<State, Opened>, IEvolve<State, Noted>
            {
                public State Apply(State s, Opened e) => s;
                public State Apply(State s, Noted e) => s;
            }
            """);

        diagnostics.Should().BeEmpty();
        sources.Should().ContainSingle().Which.Should().Be("""
            // <auto-generated/>
            #nullable enable

            namespace App;

            partial class AccountEvolver : global::Alberto.IGeneratedEvolver<global::App.State>
            {
                global::System.Type global::Alberto.IGeneratedEvolver<global::App.State>.GeneratedFor => typeof(global::App.AccountEvolver);

                global::System.Collections.Generic.IReadOnlyList<(global::System.Type EventType, global::System.Func<global::App.State, object, global::App.State> Apply)> global::Alberto.IGeneratedEvolver<global::App.State>.EvolveTable() =>
                    new (global::System.Type, global::System.Func<global::App.State, object, global::App.State>)[]
                    {
                        (typeof(global::App.Noted), (state, e) => ((global::Alberto.IEvolve<global::App.State, global::App.Noted>)this).Apply(state, (global::App.Noted)e)),
                        (typeof(global::App.Opened), (state, e) => ((global::Alberto.IEvolve<global::App.State, global::App.Opened>)this).Apply(state, (global::App.Opened)e)),
                    };
            }

            """.ReplaceLineEndings());
    }

    [Fact]
    public void Reads_the_same_interfaces_reflection_does()
    {
        // Explicit and inherited IEvolves are in; an IEvolve of another state is not, the same
        // filter EvolverDispatcher applies to GetInterfaces().
        var (sources, _) = Run($$"""
            {{Events}}

            public abstract class Base : Evolver<State>, IEvolve<State, Opened>
            {
                public State Apply(State s, Opened e) => s;
            }

            public sealed partial class Derived : Base, IEvolve<State, Noted>, IEvolve<OtherState, Other>
            {
                State IEvolve<State, Noted>.Apply(State s, Noted e) => s;
                public OtherState Apply(OtherState s, Other e) => s;
            }
            """);

        var source = sources.Should().ContainSingle().Subject;
        source.Should().Contain("typeof(global::App.Opened)").And.Contain("typeof(global::App.Noted)");
        source.Should().NotContain("Other");
    }

    [Fact]
    public void Nests_the_table_inside_partial_containing_types()
    {
        var (sources, _) = Run($$"""
            {{Events}}

            public static partial class Outer
            {
                public sealed partial class Inner : Evolver<State>, IEvolve<State, Opened>
                {
                    public State Apply(State s, Opened e) => s;
                }
            }
            """);

        sources.Single().Should().Contain("partial class Outer\n{\npartial class Inner : ".ReplaceLineEndings());
    }

    [Theory]
    [InlineData("public sealed class Plain : Evolver<State>, IEvolve<State, Opened> { public State Apply(State s, Opened e) => s; }")]
    [InlineData("public abstract partial class Abstract : Evolver<State>, IEvolve<State, Opened> { public State Apply(State s, Opened e) => s; }")]
    [InlineData("public sealed partial class Generic<T> : Evolver<State>, IEvolve<State, Opened> { public State Apply(State s, Opened e) => s; }")]
    [InlineData("public static class Outer { public sealed partial class Inner : Evolver<State>, IEvolve<State, Opened> { public State Apply(State s, Opened e) => s; } }")]
    [InlineData("public sealed partial class NotAnEvolver : IEvolve<State, Opened> { public State Apply(State s, Opened e) => s; }")]
    public void Emits_nothing_it_cannot_or_was_not_asked_to_extend(string declaration)
    {
        var (sources, diagnostics) = Run($"{Events}\n\n{declaration}");

        sources.Should().BeEmpty();
        diagnostics.Should().BeEmpty("no [AlbertoEventRegistry], so nothing asked for AOT");
    }

    [Theory]
    [InlineData("public sealed class Plain : Evolver<State>, IEvolve<State, Opened> { public State Apply(State s, Opened e) => s; }", "global::App.Plain")]
    [InlineData("public static class Outer { public sealed partial class Inner : Evolver<State>, IEvolve<State, Opened> { public State Apply(State s, Opened e) => s; } }", "global::App.Outer.Inner")]
    public void A_non_partial_evolver_is_ALB3004_when_the_compilation_has_a_registry(string declaration, string name)
    {
        var (sources, diagnostics) = Run($"{Events}\n\n{Registry}\n\n{declaration}");

        sources.Should().BeEmpty();
        var diagnostic = diagnostics.Should().ContainSingle().Subject;
        diagnostic.Id.Should().Be("ALB3004");
        diagnostic.GetMessage().Should().Contain(name);
        diagnostic.Location.Should().NotBe(Location.None);
    }

    private static (IReadOnlyList<string> Sources, IReadOnlyList<Diagnostic> Diagnostics) Run(string source) =>
        EventRegistryGeneratorTests.Run(source, new EvolverTableGenerator());
}
