// <auto-generated />
using System;
using Alberto.Orders.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Alberto.Orders.Infrastructure.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    [Migration("20260116202940_LineItemsAsJson")]
    partial class LineItemsAsJson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("orders")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Alberto.Orders.Infrastructure.Entities.OrderSummaryEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DocumentId")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Carrier")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ShippedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TenantId", "DocumentId");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_order_summaries_tenant_created");

                    b.HasIndex("TenantId", "CustomerId")
                        .HasDatabaseName("ix_order_summaries_tenant_customer");

                    b.HasIndex("TenantId", "OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_order_summaries_tenant_orderid");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_order_summaries_tenant_status");

                    b.HasIndex("TenantId", "UpdatedAt")
                        .HasDatabaseName("ix_order_summaries_tenant_updated");

                    b.ToTable("order_summaries", "orders");
                });

            modelBuilder.Entity("Alberto.Orders.Infrastructure.Entities.OrderSummaryEntity", b =>
                {
                    b.OwnsMany("Alberto.Orders.Infrastructure.Entities.OrderLineItemData", "LineItems", b1 =>
                        {
                            b1.Property<string>("OrderSummaryEntityTenantId");

                            b1.Property<string>("OrderSummaryEntityDocumentId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<Guid>("ProductId");

                            b1.Property<string>("ProductName")
                                .IsRequired();

                            b1.Property<int>("Quantity");

                            b1.Property<decimal>("Total");

                            b1.Property<decimal>("UnitPrice");

                            b1.HasKey("OrderSummaryEntityTenantId", "OrderSummaryEntityDocumentId", "__synthesizedOrdinal");

                            b1.ToTable("order_summaries", "orders");

                            b1
                                .ToJson("LineItems")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("OrderSummaryEntityTenantId", "OrderSummaryEntityDocumentId");
                        });

                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
