<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Modules\Orders\Migrations\*.sql"/>
    <EmbeddedResource Include="Modules\Payments\Migrations\*.sql"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\EventStore\Alberto.EventStore.Postgres\Alberto.EventStore.Postgres.csproj" />
    <ProjectReference Include="..\..\EventStore\Alberto.EventStore.Telemetry\Alberto.EventStore.Telemetry.csproj" />
    <ProjectReference Include="..\Alberto.ServiceDefaults\Alberto.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
