<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

    <!-- Server GC for better throughput and more aggressive collection -->
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Alberto.Example.UnitTests"/>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Modules\Orders\Migrations\*.sql"/>
    <EmbeddedResource Include="Modules\Payments\Migrations\*.sql"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\EventSourcing\Alberto.EventSourcing\Alberto.EventSourcing.csproj"/>
    <ProjectReference Include="..\..\EventStore\Alberto.EventStore.Postgres\Alberto.EventStore.Postgres.csproj"/>
    <ProjectReference Include="..\..\EventStore\Alberto.EventStore.Telemetry\Alberto.EventStore.Telemetry.csproj"/>
    <ProjectReference Include="..\..\CQRS\Alberto.CQRS\Alberto.CQRS.csproj"/>
    <ProjectReference Include="..\..\EventSourcing\Alberto.Projections.InMemory\Alberto.Projections.InMemory.csproj"/>
    <ProjectReference Include="..\Alberto.ServiceDefaults\Alberto.ServiceDefaults.csproj"/>
    <ProjectReference Include="..\..\CQRS\Alberto.CQRS.Telemetry\Alberto.CQRS.Telemetry.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI"/>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\"/>
    <Folder Include="Migrations\Generated\"/>
    <Folder Include="Modules\Orders\Subscriptions\"/>
  </ItemGroup>

</Project>
