<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.0"/>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <UserSecretsId>88bc2984-911c-4fce-8fcd-bcbe1c96f5b0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost"/>
    <PackageReference Include="Aspire.Hosting.PostgreSQL"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alberto.Example\Alberto.Example.csproj"/>
    <ProjectReference Include="..\Alberto.SqlMigrator\Alberto.SqlMigrator.csproj"/>
  </ItemGroup>

</Project>
