<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Alberto.Examples.Shared\Alberto.Examples.Shared.csproj" />
    <ProjectReference Include="..\Alberto.Orders\Alberto.Orders.csproj" />
    <ProjectReference Include="..\..\Alberto.Payments\Alberto.Payments\Alberto.Payments.csproj" />
    <ProjectReference Include="..\..\..\src\Alberto.Dcb.Telemetry\Alberto.Dcb.Telemetry.csproj" />
    <ProjectReference Include="..\..\ServiceDefaults\ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\..\src\Alberto.Dcb.Admin\Alberto.Dcb.Admin.csproj" />
    <ProjectReference Include="..\..\..\src\Alberto.Dcb.Admin.GraphQL\Alberto.Dcb.Admin.GraphQL.csproj" />
    <ProjectReference Include="..\..\..\src\Alberto.Dcb.Postgres\Alberto.Dcb.Postgres.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HotChocolate.AspNetCore" />
    <PackageReference Include="HotChocolate.Subscriptions.InMemory" />
    <PackageReference Include="HotChocolate.Types.Analyzers" />
  </ItemGroup>

</Project>
