<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <RootNamespace>Alberto.Dcb.Admin</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Alberto.Dcb\Alberto.Dcb.csproj" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="UI\EmbeddedResources\**\*" />
    </ItemGroup>
</Project>
