<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>


  <ItemGroup>
    <ProjectReference Include="../../src/Alberto.Dcb/Alberto.Dcb.csproj" />
  </ItemGroup>

</Project>
